namespace Frontend.Windows
{
    partial class Form1
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            txtDisplay = new TextBox();
            btn7 = new Button();
            btn8 = new Button();
            btn9 = new Button();
            btnOpenParenthesis = new Button();
            btnCloseParenthesis = new Button();
            btnDelete = new Button();
            btn4 = new Button();
            btn5 = new Button();
            btn6 = new Button();
            btnMultiply = new Button();
            btnDivide = new Button();
            btnClear = new Button();
            btn1 = new Button();
            btn2 = new Button();
            btn3 = new Button();
            btnAdd = new Button();
            btnSubtract = new Button();
            btnPower = new Button();
            btn0 = new Button();
            btnDot = new Button();
            btnEquals = new Button();
            SuspendLayout();
            txtDisplay.BackColor = Color.Green;
            txtDisplay.Font = new Font("Segoe UI", 18F);
            txtDisplay.ForeColor = Color.White;
            txtDisplay.Location = new Point(12, 12);
            txtDisplay.Name = "txtDisplay";
            txtDisplay.ReadOnly = true;
            txtDisplay.Size = new Size(456, 47);
            txtDisplay.TabIndex = 0;
            txtDisplay.TabStop = false;
            btn7.BackColor = Color.White;
            btn7.FlatStyle = FlatStyle.Flat;
            btn7.Font = new Font("Segoe UI", 16F);
            btn7.ForeColor = Color.Black;
            btn7.Location = new Point(12, 72);
            btn7.Name = "btn7";
            btn7.Size = new Size(60, 60);
            btn7.TabIndex = 1;
            btn7.TabStop = false;
            btn7.Text = "7";
            btn7.UseVisualStyleBackColor = false;
            btn7.Click += InputButton_Click;
            btn8.BackColor = Color.White;
            btn8.FlatStyle = FlatStyle.Flat;
            btn8.Font = new Font("Segoe UI", 16F);
            btn8.ForeColor = Color.Black;
            btn8.Location = new Point(78, 72);
            btn8.Name = "btn8";
            btn8.Size = new Size(60, 60);
            btn8.TabIndex = 2;
            btn8.TabStop = false;
            btn8.Text = "8";
            btn8.UseVisualStyleBackColor = false;
            btn8.Click += InputButton_Click;
            btn9.BackColor = Color.White;
            btn9.FlatStyle = FlatStyle.Flat;
            btn9.Font = new Font("Segoe UI", 16F);
            btn9.ForeColor = Color.Black;
            btn9.Location = new Point(144, 72);
            btn9.Name = "btn9";
            btn9.Size = new Size(60, 60);
            btn9.TabIndex = 3;
            btn9.TabStop = false;
            btn9.Text = "9";
            btn9.UseVisualStyleBackColor = false;
            btn9.Click += InputButton_Click;
            btnOpenParenthesis.BackColor = Color.DarkOrange;
            btnOpenParenthesis.FlatStyle = FlatStyle.Flat;
            btnOpenParenthesis.Font = new Font("Segoe UI", 16F);
            btnOpenParenthesis.ForeColor = Color.Black;
            btnOpenParenthesis.Location = new Point(210, 72);
            btnOpenParenthesis.Name = "btnOpenParenthesis";
            btnOpenParenthesis.Size = new Size(60, 60);
            btnOpenParenthesis.TabIndex = 4;
            btnOpenParenthesis.TabStop = false;
            btnOpenParenthesis.Text = "(";
            btnOpenParenthesis.UseVisualStyleBackColor = false;
            btnOpenParenthesis.Click += InputButton_Click;
            btnCloseParenthesis.BackColor = Color.DarkOrange;
            btnCloseParenthesis.FlatStyle = FlatStyle.Flat;
            btnCloseParenthesis.Font = new Font("Segoe UI", 16F);
            btnCloseParenthesis.ForeColor = Color.Black;
            btnCloseParenthesis.Location = new Point(276, 72);
            btnCloseParenthesis.Name = "btnCloseParenthesis";
            btnCloseParenthesis.Size = new Size(60, 60);
            btnCloseParenthesis.TabIndex = 5;
            btnCloseParenthesis.TabStop = false;
            btnCloseParenthesis.Text = ")";
            btnCloseParenthesis.UseVisualStyleBackColor = false;
            btnCloseParenthesis.Click += InputButton_Click;
            btnDelete.BackColor = Color.DarkOrange;
            btnDelete.FlatStyle = FlatStyle.Flat;
            btnDelete.Font = new Font("Segoe UI", 16F);
            btnDelete.ForeColor = Color.Black;
            btnDelete.Location = new Point(342, 72);
            btnDelete.Name = "btnDelete";
            btnDelete.Size = new Size(126, 60);
            btnDelete.TabIndex = 6;
            btnDelete.TabStop = false;
            btnDelete.Text = "Delete";
            btnDelete.UseVisualStyleBackColor = false;
            btnDelete.Click += btnDelete_Click;
            btn4.BackColor = Color.White;
            btn4.FlatStyle = FlatStyle.Flat;
            btn4.Font = new Font("Segoe UI", 16F);
            btn4.ForeColor = Color.Black;
            btn4.Location = new Point(12, 138);
            btn4.Name = "btn4";
            btn4.Size = new Size(60, 60);
            btn4.TabIndex = 7;
            btn4.TabStop = false;
            btn4.Text = "4";
            btn4.UseVisualStyleBackColor = false;
            btn4.Click += InputButton_Click;
            btn5.BackColor = Color.White;
            btn5.FlatStyle = FlatStyle.Flat;
            btn5.Font = new Font("Segoe UI", 16F);
            btn5.ForeColor = Color.Black;
            btn5.Location = new Point(78, 138);
            btn5.Name = "btn5";
            btn5.Size = new Size(60, 60);
            btn5.TabIndex = 8;
            btn5.TabStop = false;
            btn5.Text = "5";
            btn5.UseVisualStyleBackColor = false;
            btn5.Click += InputButton_Click;
            btn6.BackColor = Color.White;
            btn6.FlatStyle = FlatStyle.Flat;
            btn6.Font = new Font("Segoe UI", 16F);
            btn6.ForeColor = Color.Black;
            btn6.Location = new Point(144, 138);
            btn6.Name = "btn6";
            btn6.Size = new Size(60, 60);
            btn6.TabIndex = 9;
            btn6.TabStop = false;
            btn6.Text = "6";
            btn6.UseVisualStyleBackColor = false;
            btn6.Click += InputButton_Click;
            btnMultiply.BackColor = Color.DarkOrange;
            btnMultiply.FlatStyle = FlatStyle.Flat;
            btnMultiply.Font = new Font("Segoe UI", 16F);
            btnMultiply.ForeColor = Color.Black;
            btnMultiply.Location = new Point(210, 138);
            btnMultiply.Name = "btnMultiply";
            btnMultiply.Size = new Size(60, 60);
            btnMultiply.TabIndex = 10;
            btnMultiply.TabStop = false;
            btnMultiply.Text = "*";
            btnMultiply.UseVisualStyleBackColor = false;
            btnMultiply.Click += InputButton_Click;
            btnDivide.BackColor = Color.DarkOrange;
            btnDivide.FlatStyle = FlatStyle.Flat;
            btnDivide.Font = new Font("Segoe UI", 16F);
            btnDivide.ForeColor = Color.Black;
            btnDivide.Location = new Point(276, 138);
            btnDivide.Name = "btnDivide";
            btnDivide.Size = new Size(60, 60);
            btnDivide.TabIndex = 11;
            btnDivide.TabStop = false;
            btnDivide.Text = "/";
            btnDivide.UseVisualStyleBackColor = false;
            btnDivide.Click += InputButton_Click;
            btnClear.BackColor = Color.DarkOrange;
            btnClear.FlatStyle = FlatStyle.Flat;
            btnClear.Font = new Font("Segoe UI", 16F);
            btnClear.ForeColor = Color.Black;
            btnClear.Location = new Point(342, 138);
            btnClear.Name = "btnClear";
            btnClear.Size = new Size(126, 60);
            btnClear.TabIndex = 12;
            btnClear.TabStop = false;
            btnClear.Text = "Clear";
            btnClear.UseVisualStyleBackColor = false;
            btnClear.Click += btnClear_Click;
            btn1.BackColor = Color.White;
            btn1.FlatStyle = FlatStyle.Flat;
            btn1.Font = new Font("Segoe UI", 16F);
            btn1.ForeColor = Color.Black;
            btn1.Location = new Point(12, 204);
            btn1.Name = "btn1";
            btn1.Size = new Size(60, 60);
            btn1.TabIndex = 13;
            btn1.TabStop = false;
            btn1.Text = "1";
            btn1.UseVisualStyleBackColor = false;
            btn1.Click += InputButton_Click;
            btn2.BackColor = Color.White;
            btn2.FlatStyle = FlatStyle.Flat;
            btn2.Font = new Font("Segoe UI", 16F);
            btn2.ForeColor = Color.Black;
            btn2.Location = new Point(78, 204);
            btn2.Name = "btn2";
            btn2.Size = new Size(60, 60);
            btn2.TabIndex = 14;
            btn2.TabStop = false;
            btn2.Text = "2";
            btn2.UseVisualStyleBackColor = false;
            btn2.Click += InputButton_Click;
            btn3.BackColor = Color.White;
            btn3.FlatStyle = FlatStyle.Flat;
            btn3.Font = new Font("Segoe UI", 16F);
            btn3.ForeColor = Color.Black;
            btn3.Location = new Point(144, 204);
            btn3.Name = "btn3";
            btn3.Size = new Size(60, 60);
            btn3.TabIndex = 15;
            btn3.TabStop = false;
            btn3.Text = "3";
            btn3.UseVisualStyleBackColor = false;
            btn3.Click += InputButton_Click;
            btnAdd.BackColor = Color.DarkOrange;
            btnAdd.FlatStyle = FlatStyle.Flat;
            btnAdd.Font = new Font("Segoe UI", 16F);
            btnAdd.ForeColor = Color.Black;
            btnAdd.Location = new Point(210, 204);
            btnAdd.Name = "btnAdd";
            btnAdd.Size = new Size(60, 60);
            btnAdd.TabIndex = 16;
            btnAdd.TabStop = false;
            btnAdd.Text = "+";
            btnAdd.UseVisualStyleBackColor = false;
            btnAdd.Click += InputButton_Click;
            btnSubtract.BackColor = Color.DarkOrange;
            btnSubtract.FlatStyle = FlatStyle.Flat;
            btnSubtract.Font = new Font("Segoe UI", 16F);
            btnSubtract.ForeColor = Color.Black;
            btnSubtract.Location = new Point(276, 204);
            btnSubtract.Name = "btnSubtract";
            btnSubtract.Size = new Size(60, 60);
            btnSubtract.TabIndex = 17;
            btnSubtract.TabStop = false;
            btnSubtract.Text = "-";
            btnSubtract.UseVisualStyleBackColor = false;
            btnSubtract.Click += InputButton_Click;
            btnPower.BackColor = Color.DarkOrange;
            btnPower.FlatStyle = FlatStyle.Flat;
            btnPower.Font = new Font("Segoe UI", 16F);
            btnPower.ForeColor = Color.Black;
            btnPower.Location = new Point(342, 204);
            btnPower.Name = "btnPower";
            btnPower.Size = new Size(126, 60);
            btnPower.TabIndex = 18;
            btnPower.TabStop = false;
            btnPower.Text = "^";
            btnPower.UseVisualStyleBackColor = false;
            btnPower.Click += InputButton_Click;
            btn0.BackColor = Color.White;
            btn0.FlatStyle = FlatStyle.Flat;
            btn0.Font = new Font("Segoe UI", 16F);
            btn0.ForeColor = Color.Black;
            btn0.Location = new Point(12, 270);
            btn0.Name = "btn0";
            btn0.Size = new Size(126, 60);
            btn0.TabIndex = 19;
            btn0.TabStop = false;
            btn0.Text = "0";
            btn0.UseVisualStyleBackColor = false;
            btn0.Click += InputButton_Click;
            btnDot.BackColor = Color.White;
            btnDot.FlatStyle = FlatStyle.Flat;
            btnDot.Font = new Font("Segoe UI", 16F);
            btnDot.ForeColor = Color.Black;
            btnDot.Location = new Point(144, 270);
            btnDot.Name = "btnDot";
            btnDot.Size = new Size(60, 60);
            btnDot.TabIndex = 20;
            btnDot.TabStop = false;
            btnDot.Text = ".";
            btnDot.UseVisualStyleBackColor = false;
            btnDot.Click += InputButton_Click;
            btnEquals.BackColor = Color.DarkOrange;
            btnEquals.FlatStyle = FlatStyle.Flat;
            btnEquals.Font = new Font("Segoe UI", 16F);
            btnEquals.ForeColor = Color.Black;
            btnEquals.Location = new Point(210, 270);
            btnEquals.Name = "btnEquals";
            btnEquals.Size = new Size(258, 60);
            btnEquals.TabIndex = 21;
            btnEquals.TabStop = false;
            btnEquals.Text = "=";
            btnEquals.UseVisualStyleBackColor = false;
            btnEquals.Click += btnEquals_Click;
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.Black;
            ClientSize = new Size(480, 342);
            Controls.Add(btnEquals);
            Controls.Add(btnDot);
            Controls.Add(btn0);
            Controls.Add(btnPower);
            Controls.Add(btnSubtract);
            Controls.Add(btnAdd);
            Controls.Add(btn3);
            Controls.Add(btn2);
            Controls.Add(btn1);
            Controls.Add(btnClear);
            Controls.Add(btnDivide);
            Controls.Add(btnMultiply);
            Controls.Add(btn6);
            Controls.Add(btn5);
            Controls.Add(btn4);
            Controls.Add(btnDelete);
            Controls.Add(btnCloseParenthesis);
            Controls.Add(btnOpenParenthesis);
            Controls.Add(btn9);
            Controls.Add(btn8);
            Controls.Add(btn7);
            Controls.Add(txtDisplay);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            KeyPreview = true;
            MaximizeBox = false;
            Name = "Form1";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Functions Evaluator";
            KeyPress += Form1_KeyPress;
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private TextBox txtDisplay;
        private Button btn7;
        private Button btn8;
        private Button btn9;
        private Button btnOpenParenthesis;
        private Button btnCloseParenthesis;
        private Button btnDelete;
        private Button btn4;
        private Button btn5;
        private Button btn6;
        private Button btnMultiply;
        private Button btnDivide;
        private Button btnClear;
        private Button btn1;
        private Button btn2;
        private Button btn3;
        private Button btnAdd;
        private Button btnSubtract;
        private Button btnPower;
        private Button btn0;
        private Button btnDot;
        private Button btnEquals;
    }
}
